services:
  backend:
    build: ./backend
    container_name: docker-backend
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
    env_file: 
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: docker-frontend
    ports:
      - '5173:5173'
    depends_on: 
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
