services:
  backend:
    image: haonpdev/docker-demo-backend:latest
    ports:
      - '8000:8000'
    env_file:
      - .env

  frontend:
    image: haonpdev/docker-demo-frontend:latest
    ports:
      - '80:80'
    depends_on: 
      - backend