services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: docker-backend
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: docker-frontend
    ports:
      - '80:80'
    depends_on: 
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
