services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    image: haonpdev/docker-demo-backend:latest
    env_file:
      - .env
    ports:
      - '8000:8000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: haonpdev/docker-demo-frontend:latest
    ports:
      - '80:80'

